services:

  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - rh-network
    tty: true
    depends_on:
      - db

  db:
    image: mysql:8.4.0
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./db_init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      - MYSQL_DATABASE=rh
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - rh-network

  nginx:
    container_name: nginx
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - rh-network

networks:
  rh-network:
    driver: bridge


    